services:
  rabbitmq:
    image: 'rabbitmq:management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'   # Porta para conex√µes AMQP
      - '15672:15672' # Porta para interface de gerenciamento web
